name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  getVersion:
    uses: orkunkarakus/react-native-cross-select/.github/workflows/get-version-from-package.yml@main

  increaseVersion:
    needs: getVersion
    uses: orkunkarakus/react-native-cross-select/.github/workflows/increase-version.yml
    with:
      version: ${{ needs.getVersion.outputs.version }}
      releaseType: patch
