name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  # Get Current Version On Package Registry
  getVersion:
    uses: orkunkarakus/react-native-cross-select/.github/workflows/get-version-from-package.yml@main

  # Create New Version From Package Registry
  createNewVersion:
    needs: getVersion
    uses: orkunkarakus/react-native-cross-select/.github/workflows/increase-version.yml@main
    with:
      version: ${{ needs.getVersion.outputs.version }}
      releaseType: patch

  # Merge New Version To Branch
  saveVersion:
    needs: createNewVersion
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    uses: orkunkarakus/react-native-cross-select/.github/workflows/merge-new-version.yml@main
    with:
      version: ${{ needs.createNewVersion.outputs.version }}
      TARGET_BRANCH: main

  # Release version to npm
  release:
    needs: saveVersion
    secrets: inherit
    permissions:
      contents: write
    uses: orkunkarakus/react-native-cross-select/.github/workflows/release.yml@main
