name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  version:
    permissions:
      contents: write
    uses: orkunkarakus/react-native-cross-select/.github/workflows/version.yml@main
    with:
      branch: main
