name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  version:
    uses: orkunkarakus/react-native-cross-select/.github/workflows/version.yml@main
    with:
      branch: main
  testo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
