name: Release package
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: "https://registry.npmjs.org"

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

        # Git configiration
      - name: Git configuration
        run: |
          git config user.name "apricotify"
          git config user.email "apricotify@orkcorp.com"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

      # Create Release On Github
      - name: Create Release On Github
        run: |
          git pull
          gh release create v${{ inputs.VERSION }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: "https://registry.npmjs.org"

      # Refresh
      - name: Pull repo
        run: git pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install Dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      # Build package
      - name: Build package
        run: yarn build

      # Release package the registry
      - name: Release package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
