name: Release package
on:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/

      # Install Dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      # Build package
      - name: Build package
        run: yarn build

      # Release package
      - name: Release package
        run: yarn release:dry
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
