# Increase version from Package

name: Increase Version (From Package)
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          ref: ${{ inputs.branch }} # Set branch from top

      # Echo old version
      - name: Echo Old version
        run: echo "Old version is $(npm pkg get version)"

      # Update Package Version
      - name: Update version
        run: |
          npm view ${{ github.event.repository.name }} version
          echo "XX ${{ github.event.repository.name }}"

      # Echo new Version
      - name: Echo New version
        run: echo "New version is $(npm pkg get version)"
